"""
ADFIR Platform — Report Model
================================
Tracks every forensic report generated by the Report Generator.
The actual report file (HTML, JSON, or PDF) is stored on disk under
REPORTS_STORAGE_PATH; this model holds the metadata and integrity hash.

Each report file is itself stored as an EvidenceArtifact in the vault
to maintain the chain of custody.
"""

import enum
from sqlalchemy import Column, String, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from backend.extensions import db
from backend.models.base import UUIDPrimaryKeyMixin


class ReportFormat(enum.Enum):
    HTML = "html"
    JSON = "json"
    PDF = "pdf"


class Report(UUIDPrimaryKeyMixin, db.Model):
    """
    Metadata record for a generated forensic report file.
    """

    __tablename__ = "reports"

    # The incident this report documents.
    incident_id = Column(
        UUID(as_uuid=True),
        ForeignKey("incidents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # When the report was produced.
    generated_at = Column(DateTime(timezone=True), nullable=False, index=True)

    # Output format of the generated file.
    format = Column(String(16), nullable=False)

    # Report title, e.g. 'Forensic Report — INC-2025-00001'.
    title = Column(String(256), nullable=False)

    # SHA-256 hex digest of the report file contents.
    sha256_hash = Column(String(64), nullable=False)

    # Relative path from REPORTS_STORAGE_PATH to the file on disk.
    storage_path = Column(String(512), nullable=False)

    # 'system' for auto-generated reports, or a user UUID for manual triggers.
    generated_by = Column(String(64), nullable=False, default="system")

    # Relationship
    incident = relationship("Incident", back_populates="reports")

    def __repr__(self) -> str:
        return (
            f"<Report {self.id!s:.8} "
            f"format={self.format!r} "
            f"incident={str(self.incident_id):.8}>"
        )

    def to_dict(self) -> dict:
        return {
            "id": str(self.id),
            "incident_id": str(self.incident_id),
            "generated_at": self.generated_at.isoformat(),
            "format": self.format,
            "title": self.title,
            "sha256_hash": self.sha256_hash,
            "storage_path": self.storage_path,
            "generated_by": self.generated_by,
        }
